name: Tests
on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTUP_MAX_RETRIES: 10
  CARGO_INCREMENTAL: 1
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always

jobs:
  benchmarking:
    name: Benchmarking
    runs-on: [self-hosted, benchmarking]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: rust # MSRV
        name: use required Rust version
        run: |
          echo "WASM_BUILD_TOOLCHAIN=$(cat rust-toolchain)" >> $GITHUB_ENV
          echo ::set-output name=version::$(cat rust-toolchain)

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ steps.rust.outputs.version }}
          profile: minimal
          components: rustfmt
          override: false

      - name: Install wasm Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ steps.rust.outputs.version }}
          profile: minimal
          target: wasm32-unknown-unknown
          override: false


      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.dove
          key: ubuntu-dove-1.3.3
      - name: get Dove
        uses: pontem-network/get-dove@main
        with:
          prerelease: true
          version: 1.3.3
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build benchmarking binary
        run: make target/bench-bin

      - name: Run sp-move benchmarks
        run: make bench

      - name: Run groupsign benchmarks
        run: make run-bench-groupsign

      - name: Save results
        uses: actions/upload-artifact@v2.2.3
        with:
          name: benches
          path: target/*-bench
          if-no-files-found: warn
          retention-days: 2
